//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MySpy.rc 使用
//
#define IDS_TEXT_NOT_FOUND              1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INFO_IN_STATUS_BAR           101
#define IDD_WINDOW_INFO_VIEW_OPTIONS    102
#define IDR_HTML_SENDMSGDLG             103
#define IDD_OPTION_PROPERTYPAGE         104
#define IDD_LOAD_SAVE_PROPERTYPAGE      106
#define IDR_MAINFRAME                   128
#define IDR_MySpyTYPE                   129
#define IDB_IMAGELIST                   130
#define IDR_POPUP_ACTION                131
#define IDR_MYSPY_TOOLBAR               132
#define IDD_FIND_DLG                    134
#define IDR_MYSPY_VIEW_TOOLBAR          135
#define IDD_SEND_MSG                    139
#define IDR_TOOLBAR_MENU                140
#define IDB_CROSS                       141
#define IDB_BLANK                       142
#define IDC_CROSS1                      143
#define IDC_CROSS0                      144
#define IDR_POPUP_WININFO               145
#define IDD_COMMAND_OPTIONS_DLG         146
#define IDD_DIALOG_INPUT_DIALOG         151
#define IDC_FIND_DLG_EDIT_BOX           1000
#define IDC_CHECK_MATCHCASE             1001
#define IDC_FIND_CHECK_MATCHCASE        1002
#define IDC_FIND_FINDNEXT               1003
#define IDB_POST_MESSAGE                1011
#define IDC_COMBO_MSG                   1012
#define IDC_RADIO_UP                    1013
#define IDC_FIND_RADIO_UP               1014
#define IDC_COMBO_LPARAM                1015
#define IDC_RADIO_DOWN                  1016
#define IDC_FIND_RADIO_DOWN             1017
#define IDC_COMBO_WPARAM                1018
#define IDC_EDIT_SETTEXT                1019
#define IDC_STATIC_SETTEXT              1020
#define IDB_SEND_MESSAGE                1021
#define IDC_FIND_WHAT                   1022
#define IDC_FIND_STATIC_FINDWHAT        1023
#define IDC_FIND_STATIC_DIRECTION       1024
#define IDC_TAB1                        1025
#define IDC_FINDBYMOUSE_CAPTURE         1026
#define IDC_FINDBYMOUSE_STATIC          1027
#define IDC_FINDBYMOUSE_HIDE_MYSPY      1028
#define IDC_FINDBYMOUSE_SELECTED_HWND   1029
#define IDC_OK                          1030
#define IDC_CANCEL                      1031
#define IDC_WIN_INFO_LIST               1032
#define IDC_UP                          1033
#define IDC_DOWN                        1034
#define IDC_BUTTON1                     1035
#define IDC_LOAD_DEFAULTS               1036
#define IDC_RESPONSE_ON_SUCCESS         1037
#define IDC_RESPONSE_ON_ERROR           1038
#define IDC_NO_RESPONSE_ABOUT_COMMAND_EXECUTION 1039
#define IDC_EDIT_REPONSE_TIMEOUT        1040
#define IDC_SAVE_SETTINGS_ON_EXIT       1041
#define IDC_ACTIVATE_AFTER_ACTION       1042
#define IDC_TREE_OR_INFO_COMBO          1043
#define IDC_TREE_OR_INFO_COMBO2         1044
#define IDC_CHECK_BROADCAST             1045
#define IDC_SLIDER_TRANSPARENCY         1046
#define IDC_CHECK_TRANSPARENT           1047
#define IDC_STATIC_TRANSPARENCY         1048
#define IDC_SPIN_AUTO_REFRESH           1049
#define IDC_EDIT_AUTO_REFRESH           1050
#define IDC_BUTTON_INPUT_OK             1051
#define IDC_EDIT_INPUT                  1052
#define IDC_BUTTON_INPUT_CANCEL         1053
#define ID_VIEW_VISIBILITY              32771
#define ID_VISIBILITY_ALL               32772
#define ID_VISIBILITY_VISIBLEONLY       32773
#define ID_VISIBILITY_NONVISIBLEONLY    32774
#define ID_PARENT_ALL                   32776
#define ID_PARENT_PARENTSONLY           32777
#define ID_PARENT_CHILDONLY             32778
#define ID_VIEW_DISPLAY_IN_HEX          32781
#define IDB_VIEW_DISPLAY_IN_HEX         32782
#define IDB_SET_TOPMOST                 32783
#define IDB_ACTION_COMBO_MSG            32784
#define IDM_STAYONTOP                   32785
#define IDB_ACTION_COMBO_L              32786
#define ID_ACTION_SHOW                  32787
#define IDB_ACTION_COMBO_W              32788
#define IDB_ACTION_SHOW                 32789
#define ID_ACTION_HIDE                  32790
#define IDB_ACTION_HIDE                 32791
#define ID_ACTION_DISABLE               32792
#define IDB_ACTION_DISABLE              32793
#define ID_ACTION_ENABLE                32794
#define IDB_ACTION_ENABLE               32795
#define ID_ACTION_SETINFOREGROUND       32796
#define IDB_ACTION_SETINFOREGROUND      32797
#define ID_ACTION_LBUTTONCLICK          32798
#define IDB_ACTION_LBUTTONCLICK         32799
#define ID_ACTION_RBUTTONCLICK          32800
#define IDB_ACTION_RBUTTONCLICK         32801
#define ID_ACTION_CLOSE                 32802
#define IDB_ACTION_CLOSE                32803
#define ID_ACTION_RESTORE               32804
#define IDB_ACTION_RESTORE              32805
#define ID_ACTION_MINIMIZE              32806
#define IDB_ACTION_MINIMIZE             32807
#define ID_ACTION_RBUTTON_DBLCLICK      32808
#define IDB_ACTION_RBUTTON_DBLCLICK     32809
#define ID_ACTION_LBUTTON_DBLCLICK      32810
#define IDB_ACTION_LBUTTON_DBLCLICK     32811
#define ID_ACTION_HIGHLIGHT             32812
#define ID_ACTION_SETTOPMOST            32813
#define ID_ACTION_SETNOTOPMOST          32814
#define ID_ACTION_END                   32815
#define IDB_REFRESH                     32822
#define IDB_VIEW_VISIBLE_ONLY           32824
#define IDB_VIEW_ALL                    32825
#define IDB_VIEW_NON_VISIBLE_ONLY       32826
#define IDB_VIEW_PARENTS                32827
#define IDB_VIEW_CHILDREN_ONLY          32828
#define ID_VIEW_END                     32840
#define ID_VIEW_TOOLBARS                32841
#define ID_TOOLBARS_MAINTOOLBAR         32842
#define ID_TOOLBARS_POST_MSG_TB         32843
#define ID_TOOLBAR_MENU_CUSTOMIZE       32844
#define IDB_ACTION_HIGHLIGHT            32846
#define ID_VIEW_WINDOWINFOPANE          32847
#define ID_WINDOWINFOPANE_LISTVIEW      32848
#define ID_WINDOWINFOPANE_RICHEIDTVIEW  32849
#define ID_WININFO_OPTIONS              32850
#define IDB_FIND                        32851
#define ID_VIEW_AFTERACTIONACTIVATE     32860
#define ID_VIEW_REFRESH                 32861
#define ID_VIEW_OPTIONS                 32862
#define ID_EDIT_FILTER                  32863

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32866
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
